apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    run: web-service
spec:
 selector:
   app: goldenwaste-dep-web
 type: NodePort
 ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30454

